export const AR_LABELS = {
  // General
  dashboard: 'لوحة القيادة',
  products: 'المنتجات',
  category: 'الفئة',
  subCategory: 'الفئة الفرعية',
  brands: 'العلامات التجارية',
  sales: 'المبيعات',
  pointOfSales: 'نقطة البيع',
  refunds: 'المبالغ المستردة',
  preferencesSetting: 'إعدادات التفضيلات',
  addMenus: 'إضافة قوائم',
  manageFoodBeverages: 'إدارة قوائم الطعام والمشروبات الخاصة بك',
  madeWithLove: '@صنع بواسطة ',
  back: 'رجوع',
  expandSidebar: 'توسيع الشريط الجانبي',
  collapseSidebar: 'طي الشريط الجانبي',
  brandRestaurantAdmin: 'لوحة تحكم',
  allRightsReserved: 'جميع الحقوق محفوظة',
  // Added missing labels for ProfileBanner, ProfileCard, and AccountSettingsForm
  healthyFood: 'طعام صحي',
  followMe: 'تابعني على',
  opportunitiesApplied: 'الفرص المطبقة',
  opportunitiesWon: 'الفرص الفائزة',
  currentOpportunities: 'الفرص الحالية',
  viewPublicProfile: 'عرض الملف الشخصي العام',
  update: 'تحديث',
  profileSettings: 'إعدادات الملف الشخصي',
  accountSetting: 'إعدادات الحساب',
  companySetting: 'إعدادات الشركة',
  documents: 'المستندات',
  billing: 'الفواتير',
  notification: 'الإشعارات',
  firstName: 'الاسم الأول',
  lastName: 'اسم العائلة',
  dateOfBirth: 'تاريخ الميلاد',
  phone: 'الهاتف',
  city: 'المدينة',
  country: 'البلد',

  // --- NEW AUTH LABELS ---
  login: 'تسجيل الدخول',
  logout: 'تسجيل الخروج',
  welcomeBack: 'مرحباً بعودتك',
  emailOrUsername: 'البريد الإلكتروني أو اسم المستخدم',
  password: 'كلمة المرور',
  forgotPassword: 'هل نسيت كلمة المرور؟',
  invalidCredentials: 'البريد الإلكتروني/اسم المستخدم أو كلمة المرور غير صالحة',
  sendVerificationCode: 'إرسال رمز التحقق',
  email: 'البريد الإلكتروني',
  emailNotRegistered: 'البريد الإلكتروني غير مسجل',
  loggingIn: 'جاري تسجيل الدخول... ',
  backToLogin: 'العودة إلى تسجيل الدخول',
  enterVerificationCode: 'أدخل رمز التحقق',
  verificationCodeSent: 'تم إرسال رمز مكون من 6 أرقام إلى بريدك الإلكتروني.',
  verificationCode: 'رمز التحقق',
  verifyCode: 'التحقق من الرمز',
  invalidCode: 'الرمز غير صالح',
  resetPassword: 'إعادة تعيين كلمة المرور',
  newPassword: 'كلمة المرور الجديدة',
  confirmPassword: 'تأكيد كلمة المرور',
  updatePassword: 'تحديث كلمة المرور',
  passwordsDoNotMatch: 'كلمتا المرور غير متطابقتين',
  passwordTooShort: 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
  passwordUpdatedSuccess: 'تم تحديث كلمة المرور بنجاح!',

  // Dashboard specific
  dashboardTitle: 'لوحة القيادة',
  dashboardDescription: 'نظرة عامة على أداء عملك',
  todaysSales: 'مبيعات اليوم',
  thisMonth: 'هذا الشهر',
  todaysTransactions: 'معاملات اليوم',
  totalProducts: 'إجمالي المنتجات',
  lowStockProducts: 'منتجات منخفضة المخزون',
  expiredProducts: 'منتجات منتهية الصلاحية',
  customersWithBalance: 'العملاء الذين لديهم رصيد',
  quickActions: 'إجراءات سريعة',
  newSale: 'بيع جديد',
  addProduct: 'إضافة منتج',
  viewCustomers: 'عرض العملاء',
  viewReports: 'عرض التقارير',
  reports: 'التقارير',

  // Header specific
  posSystem: 'نظام نقاط البيع',
  users: 'المستخدمين',
  settings: 'الإعدادات',
  ahmadSai: 'أحمد صالح',

  // Product Page specific
  productManagement: 'إدارة المنتجات',
  productManagementDescription: 'عرض وإدارة المنتجات والفئات والعلامات التجارية.',
  productListing: 'قائمة المنتجات',
  productListingDescription: 'إدارة المنتجات المتوفرة في المخزون',
  addNewProduct: 'إضافة منتج جديد',
  editProduct: 'تعديل المنتج',
  warehouseManagement: 'إدارة المستودعات',
  productName: 'اسم المنتج',
  categoryName: 'الفئة',
  price: 'السعر',
  stock: 'المخزون',
  actions: 'إجراءات',
  edit: 'تعديل',
  delete: 'حذف',
  saveProduct: 'حفظ المنتج',
  cancel: 'إلغاء',
  searchPlaceholder: 'ابحث بالاسم، الباركود، أو الفئة...',
  filterByStatus: 'تصفية حسب الحالة',
  allProducts: 'كل المنتجات',
  lowStock: 'مخزون منخفض',
  expired: 'منتهي الصلاحية',
  newlyAdded: 'أضيف حديثاً',
  expiryDate: 'تاريخ الانتهاء',
  numberOfCategories: 'عدد الفئات',
  numberOfBrands: 'عدد العلامات التجارية',

  // Multi-unit product specific labels (updated for dynamic units)
  multiUnitProduct: 'منتج متعدد الوحدات',
  initialQuantityHighestUnit: 'الكمية الأولية (أعلى وحدة)', // Replaces numBoxes
  totalPurchasePrice: 'إجمالي سعر الشراء',
  unitName: 'اسم الوحدة', // New
  barcode: 'الباركود',
  subUnitsPerThisUnit: 'الوحدات الفرعية لكل وحدة', // Replaces cartonsPerBox, piecesPerCarton
  sellingPrice: 'سعر البيع', // Generic selling price
  totalQuantity: 'الكمية الإجمالية', // Generic total quantity
  costPerUnit: 'التكلفة لكل وحدة', // Generic cost per unit
  basicInformation: 'المعلومات الأساسية',
  unitInformation: 'معلومات الوحدات', // Changed from singular
  autoCalculations: 'الحسابات التلقائية',
  calculate: 'حساب',
  generateBarcode: 'توليد باركود',
  addUnitLevel: 'إضافة مستوى وحدة', // New
  remove: 'إزالة', // New
  parentUnit: 'وحدة الأبوين', // New, if needed for context

  // Sales Pages Specific
  salesToday: 'مبيعات اليوم',
  salesTodayDescription: 'عرض ملخص لمبيعاتك لليوم الحالي.',
  salesHistory: 'سجل المبيعات',
  salesHistoryDescription: 'تصفح وابحث في سجل المبيعات الخاص بك.',
  totalSales: 'إجمالي المشتريات',
  numberOfOrders: 'عدد الطلبات',
  avgOrderValue: 'متوسط قيمة الطلب',
  filterByDate: 'تصفية حسب التاريخ',
  from: 'من',
  to: 'إلى',
  applyFilters: 'تطبيق الفلاتر',
  resetFilters: 'إعادة تعيين',
  orderId: 'رقم الطلب',
  date: 'التاريخ',
  time: 'الوقت',
  customerName: 'اسم العميل',
  totalAmount: 'المبلغ الإجمالي',
  paymentMethod: 'طريقة الدفع',
  status: 'الحالة',
  viewDetails: 'عرض التفاصيل',
  printReceipt: 'طباعة الإيصال',
  noSalesFound: 'لم يتم العثور على مبيعات تطابق الفلاتر.',
  noSalesToday: 'لا توجد مبيعات مسجلة لليوم حتى الآن.',

  // New Sales Management Page Specific
  salesManagement: 'إدارة المبيعات',
  salesManagementDescription: 'عرض وتصفية وتصدير جميع معاملات البيع.',
  viewAllSales: 'عرض كل المبيعات',
  salesReports: 'تقارير المبيعات',
  customerAccounts: 'حسابات العملاء',
  searchByCustomerOrInvoice: 'ابحث بالعميل، الفاتورة، أو الهاتف...',
  paymentType: 'نوع الدفع',
  seller: 'البائع',
  paid: 'مدفوع',
  remaining: 'المتبقي',
  partial: 'جزئي',
  due: 'مستحق',
  totalSalesToday: 'إجمالي مبيعات اليوم',
  totalPayments: 'إجمالي المدفوعات',
  creditSales: 'مبيعات آجلة',
  invoiceCount: 'عدد الفواتير',
  collectionRate: 'نسبة التحصيل',
  generateReport: 'إنشاء تقرير',
  reportType: 'نوع التقرير',
  totalSalesReport: 'تقرير إجمالي المبيعات',
  salesByCustomerReport: 'تقرير المبيعات حسب العميل',
  salesByUserReport: 'تقرير المبيعات حسب المستخدم',
  salesByPaymentTypeReport: 'تقرير المبيعات حسب نوع الدفع',
  exportExcel: 'تصدير Excel',
  exportPDF: 'تصدير PDF',
  printReport: 'طباعة التقرير',
  lastPayment: 'آخر دفعة',
  dueAmount: 'المبلغ المستحق',
  amountPaid: 'المبلغ المدفوع',
  notes: 'ملاحظات',

  // Customer Accounts Specific
  searchByCustomerNameOrPhone: 'ابحث بالاسم أو رقم الهاتف...',
  allCustomers: 'كل العملاء',
  hasBalance: 'عليه رصيد',
  noBalance: 'ليس عليه رصيد',
  customerStatement: 'كشف حساب العميل',
  transactionHistory: 'سجل الحركات',
  debit: 'مدين',
  // FIX: An object literal cannot have multiple properties with the same name.
  creditTerm: 'دائن',
  balance: 'الرصيد',
  invoice: 'فاتورة',
  paymentReceived: 'دفعة مستلمة',

  // Category Management Page Specific (Updated)
  categoryManagement: 'إدارة الفئات',
  categoryManagementDescription: 'تنظيم فئات المنتجات الرئيسية والفرعية.',
  searchByCategoryName: 'ابحث باسم الفئة...',
  allStatuses: 'كل الحالات',
  active: 'نشط',
  inactive: 'غير نشط',
  sortBy: 'ترتيب حسب',
  sortByNameAsc: 'الاسم (أ-ي)',
  sortByNameDesc: 'الاسم (ي-أ)',
  sortByDateAsc: 'الأقدم أولاً',
  sortByDateDesc: 'الأحدث أولاً',
  addNewCategory: 'إضافة فئة جديدة',
  importCategories: 'استيراد',
  exportCategories: 'تصدير',
  productCount: 'عدد المنتجات',
  createdDate: 'تاريخ الإنشاء',

  // Modal specific
  categoryDetails: 'تفاصيل الفئة',
  nameArabic: 'الاسم (بالعربية)',
  description: 'الوصف',
  parentCategory: 'الفئة الرئيسية',
  noParentCategory: 'لا يوجد (فئة رئيسية)',
  save: 'حفظ',

  // Deletion confirmation
  confirmDeleteTitle: 'تأكيد الحذف',
  confirmDeleteMessage: 'هل أنت متأكد أنك تريد حذف هذه الفئة؟',
  confirmDeleteWithChildren:
    'لا يمكن حذف هذه الفئة لأنها تحتوي على فئات فرعية. يرجى حذف الفئات الفرعية أولاً.',
  confirmDeleteWithProducts:
    'تحتوي هذه الفئة على منتجات. سيؤدي حذفها إلى جعل هذه المنتجات بدون فئة. هل تريد المتابعة؟',

  // Brand Management Page Specific
  brandManagement: 'إدارة العلامات التجارية',
  brandManagementDescription: 'إنشاء وتحرير وحذف العلامات التجارية للمنتجات.',
  searchByBrandName: 'ابحث باسم العلامة التجارية...',
  brandName: 'اسم العلامة التجارية',
  addNewBrand: 'إضافة علامة تجارية جديدة',
  brandDetails: 'تفاصيل العلامة التجارية',
  confirmDeleteBrandMessage: 'هل أنت متأكد أنك تريد حذف هذه العلامة التجارية؟',
  confirmDeleteBrandWithProducts:
    'هذه العلامة التجارية مرتبطة بمنتجات. سيؤدي حذفها إلى جعل هذه المنتجات بدون علامة تجارية. هل تريد المتابعة؟',

  // POS Page Specific
  invoiceNumber: 'رقم الفاتورة',
  // FIX: Renamed 'cashier' to 'posCashier' to avoid duplicate key error.
  posCashier: 'الكاشير',
  searchProductPlaceholder: 'ابحث بالاسم أو امسح الباركود...',
  unit: 'الوحدة',
  quantity: 'الكمية',
  discount: 'الخصم',
  invoiceDiscount: 'خصم على الفاتورة',
  totalDiscount: 'إجمالي الخصم',
  subtotal: 'المجموع الفرعي',
  tax: 'الضريبة',
  grandTotal: 'المجموع الكلي',
  selectCustomer: 'اختر عميل...',
  addNewCustomer: 'إضافة عميل جديد',
  quickProducts: 'المنتجات السريعة',
  holdSale: 'تعليق البيع',
  payNow: 'الدفع الآن',
  cash: 'نقدي',
  card: 'بطاقة',
  credit: 'آجل',
  visa: 'فيزا',
  payment: 'الدفع',
  amountReceived: 'المبلغ المستلم',
  change: 'الباقي',
  confirmPayment: 'تأكيد الدفع',
  saleCompleted: 'اكتملت عملية البيع بنجاح!',
  startNewSale: 'بدء عملية بيع جديدة',
  heldInvoices: 'الفواتير المعلقة',
  restore: 'استعادة',
  noItemsInCart: 'لا توجد أصناف في السلة.',
  selectRegisteredCustomerForCredit: 'للمبيعات الآجلة, يرجى اختيار عميل مسجل.',
  autoPrintInvoice: 'طباعة الفاتورة تلقائياً',
  returnProduct: 'إرجاع منتج',
  returnInvoice: 'فاتورة إرجاع',
  searchInvoicePlaceholder: 'ابحث برقم الفاتورة أو اسم العميل...',
  productsToReturn: 'المنتجات المراد إرجاعها',
  returnQuantity: 'كمية الإرجاع',
  totalReturnValue: 'إجمالي قيمة الإرجاع',
  confirmReturn: 'تأكيد الإرجاع',
  returnCompleted: 'تم الإرجاع بنجاح!',
  originalQuantity: 'الكمية الأصلية',

  // Wholesale POS Page Specific
  wholesalePOS: 'نقطة بيع الجملة',
  selectWholesaleCustomer: 'اختر عميل جملة...',
  addNewWholesaleCustomer: 'إضافة عميل جملة جديد',
  companyName: 'اسم الشركة',
  address: 'العنوان',
  creditSale: 'بيع آجل',
  dueDate: 'تاريخ الاستحقاق',
  confirmCreditSale: 'تأكيد البيع الآجل',
  clearCart: 'إفراغ السلة',
  totalItems: 'إجمالي الأصناف',
  filterByCategory: 'تصفية حسب الفئة',
  filterByBrand: 'تصفية حسب العلامة التجارية',
  allCategories: 'كل الفئات',
  allBrands: 'كل العلامات',
  addToCart: 'أضف للسلة',
  availableStock: 'المخزون المتوفر',
  checkout: 'الدفع',
  // customerDetails: 'تفاصيل العميل', // 'customerDetails' key is duplicated. Using the one from Purchases section.
  noCustomerSelected: 'لم يتم اختيار عميل',
  orderSummary: 'ملخص الطلب',
  // FIX: Add 'customerDetails' to resolve type error in WholesalePOSPage.tsx
  customerDetails: 'تفاصيل العميل',

  // Refunds Page Specific
  refundsManagement: 'إدارة المبالغ المستردة',
  refundsManagementDescription: 'تسجيل وإدارة عمليات إرجاع المنتجات والمبالغ المستردة.',
  addNewRefund: 'إضافة إرجاع جديد',
  originalInvoiceNumber: 'رقم الفاتورة الأصلية',
  refundedProducts: 'المنتجات المرتجعة',
  refundAmount: 'المبلغ المسترد',
  refundDate: 'تاريخ الإرجاع',
  refundMethod: 'طريقة الاسترداد',
  reasonForRefund: 'سبب الإرجاع (اختياري)',
  customerCredit: 'رصيد العميل',
  fullRefund: 'إرجاع كامل',
  partialRefund: 'إرجاع جزئي',
  searchByInvoiceOrCustomer: 'ابحث برقم الفاتورة أو اسم العميل...',
  findInvoice: 'بحث عن الفاتورة',
  invoiceNotFound: 'لم يتم العثور على الفاتورة.',
  selectProductsToRefund: 'اختر المنتجات المراد إرجاعها:',
  refundQuantity: 'الكمية المرتجعة',
  saveRefund: 'حفظ الإرجاع',
  invoiceDetails: 'تفاصيل الفاتورة',
  maxQuantity: 'الحد الأقصى',

  // FIX: Add missing labels for PaymentMethodsPage.tsx to resolve type errors.
  // Payment Methods Page Specific
  paymentMethodsManagement: 'إدارة طرق الدفع',
  paymentMethodsManagementDescription: 'إعداد وتخصيص طرق الدفع المتاحة في نقطة البيع.',
  addNewPaymentMethod: 'إضافة طريقة دفع جديدة',
  searchByPaymentMethodName: 'ابحث باسم طريقة الدفع...',
  paymentMethodDetails: 'تفاصيل طريقة الدفع',
  paymentMethodName: 'اسم طريقة الدفع',
  paymentMethodType: 'نوع طريقة الدفع',
  digitalWallet: 'محفظة رقمية',
  other: 'أخرى',

  // Preferences Page Specific
  preferences: 'التفضيلات',
  preferencesDescription: 'إدارة الإعدادات العامة للنظام والتكوينات الرئيسية.',
  generalSettings: 'الإعدادات العامة للنظام',
  businessName: 'اسم النشاط التجاري',
  uploadLogo: 'تحميل الشعار',
  defaultCurrency: 'العملة الافتراضية',
  dateFormat: 'تنسيق التاريخ',
  timeFormat: 'تنسيق الوقت',
  defaultLanguage: 'اللغة الافتراضية للنظام',
  invoiceAndSalesSettings: 'إعدادات الفواتير والمبيعات',
  vatPercentage: 'نسبة ضريبة القيمة المضافة (%)',
  invoiceNumberFormat: 'تنسيق ترقيم الفواتير',
  invoiceFooterText: 'النص التذييلي الافتراضي للفاتورة',
  // autoPrintInvoice: 'طباعة الفواتير تلقائياً بعد كل عملية بيع', // This is duplicated, using the one from POS
  sellWithoutStock: 'السماح ببيع المنتجات التي لا يوجد لها مخزون',
  allowSellingZeroStock: 'السماح ببيع المنتجات ذات المخزون الصفر',
  userRolesAndPermissions: 'أدوار المستخدمين والصلاحيات',
  sessionDuration: 'مدة جلسة تسجيل الدخول (بالدقائق)',
  allowUserCreation: 'السماح للمسؤول بإنشاء مستخدمين جدد',
  admin: 'المسؤول',
  manager: 'المدير',
  cashier: 'كاشير',
  inventoryAndProductsSettings: 'إعدادات المخزون والمنتجات',
  defaultMeasurementUnits: 'وحدات القياس الافتراضية (مفصولة بفاصلة)',
  minStockLevel: 'الحد الأدنى لمستوى المخزون للتنبيه',
  enableLowStockNotifications: 'تفعيل إشعارات انخفاض المخزون',
  paymentAndCurrencyOptions: 'خيارات الدفع والعملة',
  enablePaymentMethods: 'تفعيل طرق الدفع',
  allowCash: 'السماح بالنقد',
  allowCard: 'السماح بالبطاقة',
  allowCredit: 'السماح بالآجل',
  notificationsAndAlerts: 'الإشعارات والتنبيهات',
  enableOverdueNotifications: 'تفعيل إشعارات الدفعات المتأخرة',
  enableAutoNotifications: 'تفعيل الإشعارات التلقائية (بريد إلكتروني/واتساب)',
  otherOptions: 'خيارات أخرى',
  databaseBackup: 'نسخ احتياطي لقاعدة البيانات',
  restoreFromBackup: 'استعادة من نسخة احتياطية',
  interfaceMode: 'وضع الواجهة',
  lightMode: 'فاتح',
  darkMode: 'داكن',
  systemVersion: 'إصدار النظام',
  saveChanges: 'حفظ التغييرات',
  changesSavedSuccessfully: 'تم حفظ التغييرات بنجاح!',

  // User Management Page Specific
  userManagement: 'إدارة المستخدمين',
  userManagementDescription: 'إدارة مستخدمي النظام وتعيين الأدوار والصلاحيات.',
  
  // Admin Dashboard Specific
  adminDashboard: 'لوحة تحكم المسؤول',
  adminDashboardDescription: 'إدارة المتاجر وإعدادات النظام',
  storeManagement: 'إدارة المتاجر',
  storeManagementDescription: 'إنشاء وإدارة المتاجر في النظام',
  systemSettings: 'إعدادات النظام',
  systemSettingsDescription: 'صفحة إعدادات النظام قريباً...',
  usersAndPermissions: 'المستخدمون والصلاحيات',
  usersAndPermissionsDescription: 'صفحة إدارة المستخدمين قريباً...',
  trialAccounts: 'الحسابات التجريبية',
  createNewStore: 'إنشاء متجر جديد',
  editStore: 'تعديل المتجر',
  storeName: 'اسم المتجر',
  storeNumber: 'رقم المتجر',
  prefix: 'البادئة',
  createdAt: 'تاريخ الإنشاء',
  noStoresFound: 'لم يتم العثور على متاجر. قم بإنشاء متجرك الأول للبدء.',
  areYouSureDeleteStore: 'هل أنت متأكد من حذف هذا المتجر؟ لا يمكن التراجع عن هذا الإجراء.',
  storeCreatedSuccessfully: 'تم إنشاء المتجر بنجاح!',
  defaultAdminUserCreated: 'تم إنشاء مستخدم المسؤول الافتراضي:',
  pleaseSaveCredentials: 'يرجى حفظ هذه البيانات بشكل آمن.',
  createDefaultStoreAdmin: 'إنشاء مستخدم مسؤول افتراضي للمتجر',
  adminEmail: 'البريد الإلكتروني للمسؤول',
  adminPassword: 'كلمة مرور المسؤول',
  adminName: 'اسم المسؤول (اختياري)',
  adminNamePlaceholder: 'مسؤول المتجر - {name}',
  defaultAdminDescription: 'سيتم إنشاء مستخدم مسؤول افتراضي لهذا المتجر. سيتم إنشاء اسم المستخدم تلقائياً من البريد الإلكتروني.',
  lowercaseLettersNumbersOnly: 'أحرف صغيرة وأرقام وشرطة سفلية فقط',
  usedForCollectionNames: 'تُستخدم لأسماء المجموعات (مثل {prefix}_products)',
  failedToLoadStores: 'فشل تحميل المتاجر',
  failedToSaveStore: 'فشل حفظ المتجر',
  failedToDeleteStore: 'فشل حذف المتجر',
  
  // Merchant & Terminal Management
  merchantTerminals: 'إدارة أجهزة الدفع',
  merchantTerminalsDescription: 'إدارة التجار وأجهزة الدفع الطرفية (VX990)',
  paymentTerminalManagement: 'إدارة أجهزة الدفع',
  manageMerchantsAndTerminals: 'إدارة التجار وأجهزة الدفع الطرفية لتكامل Verifone VX990',
  merchants: 'التجار',
  terminals: 'أجهزة الدفع',
  addMerchant: 'إضافة تاجر',
  addTerminal: 'إضافة جهاز',
  editMerchant: 'تعديل تاجر',
  createMerchant: 'إنشاء تاجر',
  editTerminal: 'تعديل جهاز',
  createTerminal: 'إنشاء جهاز',
  merchantName: 'اسم التاجر',
  merchantId: 'رقم التاجر (MID)',
  storeId: 'رقم المتجر',
  maintenance: 'صيانة',
  searchMerchants: 'ابحث عن التجار...',
  searchTerminals: 'ابحث عن أجهزة الدفع...',
  noMerchantsFound: 'لم يتم العثور على تجار',
  noTerminalsFound: 'لم يتم العثور على أجهزة دفع',
  loading: 'جاري التحميل...',
  terminalName: 'اسم الجهاز',
  terminalId: 'رقم الجهاز (TID)',
  ipAddress: 'عنوان IP',
  port: 'المنفذ',
  connectionType: 'نوع الاتصال',
  testMode: 'وضع الاختبار',
  timeout: 'انتهاء الوقت (ملي ثانية)',
  enableTestMode: 'تفعيل وضع الاختبار',
  selectMerchant: 'اختر تاجر',
  selectStatus: 'اختر الحالة',
  selectConnectionType: 'اختر نوع الاتصال',
  filterByMerchant: 'تصفية حسب التاجر',
  allMerchants: 'جميع التجار',
  ethernet: 'إيثرنت',
  usb: 'USB',
  serial: 'سيريال',
  test: 'اختبار',
  testConnection: 'اختبار الاتصال',
  testing: 'جاري الاختبار...',
  create: 'إنشاء',
  deleteMerchantConfirm: 'هل أنت متأكد من حذف هذا التاجر؟ سيتم حذف الأجهزة المرتبطة به أيضاً.',
  deleteTerminalConfirm: 'هل أنت متأكد من حذف هذا الجهاز؟',
  createMerchantFirst: 'يرجى إنشاء تاجر أولاً',
  terminalConnectionSuccessful: 'تم الاتصال بالجهاز بنجاح!',
  connectionTestFailed: 'فشل اختبار الاتصال',
  failedToLoadMerchants: 'فشل تحميل التجار',
  failedToLoadTerminals: 'فشل تحميل أجهزة الدفع',
  failedToSaveMerchant: 'فشل حفظ التاجر',
  failedToSaveTerminal: 'فشل حفظ الجهاز',
  failedToDeleteMerchant: 'فشل حذف التاجر',
  failedToDeleteTerminal: 'فشل حذف الجهاز',
  terminalType: 'نوع الجهاز',
  storeBased: 'مربوط بالمتجر',
  merchantBased: 'مربوط بالتاجر',
  selectTerminalType: 'اختر نوع الجهاز',
  storeBasedTerminal: 'جهاز مرتبط بالمتجر',
  merchantBasedTerminal: 'جهاز مرتبط بالتاجر',
  filterByStore: 'تصفية حسب المتجر',
  allStores: 'جميع المتاجر',
  searchByUserNameOrRole: 'ابحث بالاسم، اسم المستخدم، أو الدور...',
  addNewUser: 'إضافة مستخدم جديد',
  fullName: 'الاسم الكامل',
  username: 'اسم المستخدم / البريد الإلكتروني',
  role: 'الدور',
  permissions: 'صلاحيات الوصول',
  lastLogin: 'آخر تسجيل دخول',
  userDetails: 'تفاصيل المستخدم',
  // password: 'كلمة المرور', // DUPLICATE
  // confirmPassword: 'تأكيد كلمة المرور', // DUPLICATE
  screenAccessPermissions: 'صلاحيات الوصول للشاشات',
  // resetPassword: 'إعادة تعيين كلمة المرور', // DUPLICATE

  // Screen Permissions
  permissionDashboard: 'لوحة القيادة',
  permissionProducts: 'المنتجات',
  permissionCategories: 'الفئات',
  permissionBrands: 'العلامات التجارية',
  permissionSalesToday: 'مبيعات اليوم',
  permissionSalesHistory: 'سجل المبيعات',
  permissionPosRetail: 'نقطة البيع (تجزئة)',
  permissionPosWholesale: 'نقطة البيع (جملة)',
  permissionRefunds: 'المبالغ المستردة',
  permissionPreferences: 'التفضيلات',
  permissionUsers: 'إدارة المستخدمين',
  permissionPurchases: 'المشتريات',
  permissionExpenses: 'المصروفات',

  // Purchases Page Specific
  purchases: 'المشتريات',
  purchaseManagement: 'إدارة المشتريات',
  purchaseManagementDescription: 'تسجيل وتتبع وإدارة جميع مشتريات الموردين.',
  poNumber: 'رقم طلب الشراء',
  supplier: 'المورد',
  itemsCount: 'عدد الأصناف',
  markAsReceived: 'استلام الطلب',
  partiallyReceived: 'تم الاستلام جزئياً',
  received: 'تم الاستلام',
  pending: 'قيد الانتظار',
  cancelled: 'ملغى',
  completed: 'مكتمل',
  bankTransfer: 'تحويل بنكي',
  addNewPurchase: 'إضافة شراء جديد',
  purchaseDetails: 'تفاصيل الشراء',
  productSelection: 'اختيار المنتج',
  unitCost: 'تكلفة الوحدة',
  viewPurchaseDetails: 'عرض تفاصيل الشراء',
  receivePurchase: 'استلام الشراء',
  printPurchaseOrder: 'طباعة طلب الشراء',
  purchaseDate: 'تاريخ الشراء',
  selectSupplier: 'اختر مورد...',
  addNewSupplier: 'إضافة مورد جديد',
  searchByPOorSupplier: 'ابحث برقم الطلب أو اسم المورد...',
  cheque: 'شيك',
  chequeNumber: 'رقم الشيك',
  chequeAmount: 'مبلغ الشيك',
  chequeDueDate: 'تاريخ استحقاق الشيك',
  bankName: 'اسم البنك',
  chequeNotes: 'ملاحظات الشيك',
  addPayment: 'إضافة دفعة',
  supplierPayment: 'دفعة للمورد',
  paymentAmount: 'مبلغ الدفعة',
  paymentDate: 'تاريخ الدفعة',
  supplierDetails: 'تفاصيل المورد',
  contactPerson: 'الشخص المسؤول',
  // email: 'البريد الإلكتروني', // DUPLICATE
  filterBySupplier: 'تصفية حسب المورد',
  allSuppliers: 'كل الموردين',
  totalPurchases: 'إجمالي المشتريات',
  // totalPaid: 'إجمالي المدفوعات', // FIX: Renamed to avoid duplicate key.
  supplierTotalPaid: 'إجمالي المدفوعات',
  remainingBalance: 'الرصيد المتبقي',
  supplierOwesYou: 'المورد مدين لك',
  youOweSupplier: 'أنت مدين للمورد',
  supplierBalance: 'رصيد المورد',
  // NEW LABELS FOR PURCHASES REFACTOR
  purchaseOrders: 'أوامر الشراء',
  supplierAccounts: 'حسابات الموردين',
  purchaseReports: 'تقارير المشتريات',
  totalDue: 'إجمالي المستحق',
  supplierStatement: 'كشف حساب المورد',
  paymentMade: 'دفعة مسددة',
  purchaseReportBySupplier: 'تقرير المشتريات حسب المورد',
  purchaseReportByProduct: 'تقرير المشتريات حسب المنتج',
  totalPurchaseReport: 'تقرير إجمالي المشتريات',
  searchBySupplierNameOrPhone: 'ابحث بالاسم أو رقم الهاتف...',
  purchaseOrder: 'أمر شراء',

  // Expenses Page Specific
  expenses: 'المصروفات',
  expenseManagement: 'إدارة المصروفات',
  expenseManagementDescription: 'تسجيل وتتبع وإدارة جميع المصروفات المالية.',
  addNewExpense: 'إضافة مصروف جديد',
  expenseNumber: 'رقم المصروف',
  expenseCategory: 'فئة المصروف',
  responsiblePerson: 'الموظف / القسم المسؤول',
  // FIX: Add missing 'amount' label to fix type error in ExpensesPage.tsx
  amount: 'المبلغ',
  unpaid: 'غير مدفوع',
  searchByExpenseDetails: 'ابحث بالرقم، الفئة، أو المسؤول...',
  expenseDetails: 'تفاصيل المصروف',

  // Cheques Page Specific
  cheques: 'الشيكات',
  chequeManagement: 'إدارة الشيكات',
  chequeManagementDescription: 'عرض وتتبع حالة جميع الشيكات الصادرة والواردة.',
  chequeCalendar: 'تقويم الشيكات',
  chequeStatus: 'حالة الشيك',
  changeStatus: 'تغيير الحالة',
  cleared: 'تم الصرف',
  bounced: 'مرتجع',
  // FIX: Add 'chequeDetails' to resolve type errors in PurchasesPage.tsx and ChequesPage.tsx
  chequeDetails: 'تفاصيل الشيك',
  // New labels for enhancement
  overdue: 'متأخرة الاستحقاق',
  dueToday: 'مستحقة اليوم',
  dueThisWeek: 'مستحقة هذا الأسبوع',
  allDates: 'كل التواريخ',
  searchByChequeOrSupplier: 'ابحث برقم الشيك أو المورد...',
  filterByDueDate: 'تصفية حسب تاريخ الاستحقاق',
  listView: 'عرض القائمة',
  calendarView: 'عرض التقويم',
  totalPending: 'إجمالي المعلق',
  totalOverdue: 'إجمالي المتأخر',
  totalBounced: 'إجمالي المرتجع',
  totalCleared: 'إجمالي المصروف',
  chequeNumberShort: 'رقم الشيك',

  // Product Performance & Insights
  productPerformanceInsights: 'أداء المنتج والرؤى',
  timeRange: 'النطاق الزمني',
  today: 'اليوم',
  thisWeek: 'هذا الأسبوع',
  last3Months: 'آخر 3 أشهر',
  thisYear: 'هذا العام',
  bestSelling: 'الأكثر مبيعًا',
  leastSelling: 'الأقل مبيعًا',
  mostProfitable: 'الأكثر ربحية',
  leastProfitable: 'الأقل ربحية',
  mostDemanded: 'الأكثر طلبًا (كمية)',
  totalItemsSold: 'إجمالي الأصناف المباعة',
  avgSellingPrice: 'متوسط سعر البيع',
  bestSellingProduct: 'المنتج الأكثر مبيعًا',
  leastSellingProduct: 'المنتج الأقل مبيعًا',
  rank: 'الترتيب',
  salesCount: 'عدد المبيعات',
  revenue: 'الإيرادات',
  profitMargin: 'هامش الربح',
  // FIX: Renamed 'change' to 'percentageChange' to avoid duplicate key error.
  percentageChange: 'التغير (%)',
  salesTrend: 'اتجاه المبيعات',
  salesValue: 'قيمة المبيعات',
  insights: 'الرؤى والتحليلات',

  // Other
  gridView: 'عرض شبكي',
  tableView: 'عرض جدولي',

  // Mobile Recharge
  rechargeMobileBalance: 'شحن رصيد الجوال',
  linkPay: 'شحن رصيد وطنية',

  // Customer Balance Operations
  addBalance: 'إضافة دفعة',
  addDebt: 'خصم من الرصيد',
  payDebt: ' إضافة رصيد',
  deductBalance: ' إضافة دين ',
};
