import { AR_LABELS } from '@/shared/constants';
import type { AccountsLabels } from './types';

export const CUSTOMER_ACCOUNTS_LABELS: AccountsLabels = {
  searchPlaceholder: AR_LABELS.searchByCustomerNameOrPhone,
  addNewEntity: AR_LABELS.addNewCustomer,
  entityName: AR_LABELS.customerName,
  statementTitle: AR_LABELS.customerStatement,
  totalDebt: AR_LABELS.totalDebt,
  totalPayments: AR_LABELS.totalPayments,
  balance: AR_LABELS.balance,
  lastPayment: AR_LABELS.lastPayment,
  actions: AR_LABELS.actions,
  addPayment: AR_LABELS.addPayment,
  allFilter: AR_LABELS.allCustomers,
  debtorFilter: AR_LABELS.debtorCustomers,
  creditorFilter: AR_LABELS.creditorCustomers,
  totalCount: 'إجمالي عدد العملاء',
  totalDueAmount: 'إجمالي المبلغ المستحق',
  countWithDebt: 'عدد العملاء ذوي الدين',
  receiptVoucherCount: 'عدد سندات القبض',
  receiptVoucherTotal: 'إجمالي سندات القبض',
  noResults: 'لا توجد نتائج',
  noEntities: 'لا يوجد عملاء',
  noResultsHint: 'لا توجد نتائج تطابق معايير البحث.',
  noEntitiesHint: 'ابدأ بإضافة عميل جديد.',
  confirmDeleteMessage: 'هل أنت متأكد من حذف هذا العميل؟',
  deleteSuccess: 'تم حذف العميل بنجاح',
  deleteFailed: 'فشل حذف العميل. يرجى المحاولة مرة أخرى.',
  updateFailed: 'فشل تحديث العميل. يرجى المحاولة مرة أخرى.',
  onlyPaymentTransactionsEditable: AR_LABELS.onlyPaymentTransactionsEditable,
  selectTransactionToEditOrDelete: AR_LABELS.selectTransactionToEditOrDelete,
  editTransaction: AR_LABELS.editTransaction,
  deleteTransaction: AR_LABELS.deleteTransaction,
  confirmDeletePaymentTitle: AR_LABELS.confirmDeletePaymentTitle,
  confirmDeletePaymentMessage: AR_LABELS.confirmDeletePaymentMessage,
  printReceipt: AR_LABELS.printReceipt,
  printSummaryOnly: 'طباعة الملخص فقط',
};

export const SUPPLIER_ACCOUNTS_LABELS: AccountsLabels = {
  searchPlaceholder: AR_LABELS.searchBySupplierNameOrPhone,
  addNewEntity: AR_LABELS.addNewSupplier,
  entityName: 'اسم المورد',
  statementTitle: AR_LABELS.supplierStatement,
  totalDebt: AR_LABELS.totalPurchases,
  totalPayments: AR_LABELS.supplierTotalPaid,
  balance: AR_LABELS.balance,
  lastPayment: AR_LABELS.lastPayment,
  actions: AR_LABELS.actions,
  addPayment: AR_LABELS.addPayment,
  allFilter: AR_LABELS.allSuppliers,
  debtorFilter: 'الموردين المدينين',
  creditorFilter: 'الموردين الدائنين',
  totalCount: 'إجمالي عدد الموردين',
  totalDueAmount: 'إجمالي المبلغ المستحق',
  countWithDebt: 'عدد الموردين ذوي الدين',
  receiptVoucherCount: 'عدد سندات الصرف',
  receiptVoucherTotal: 'إجمالي سندات الصرف',
  noResults: 'لا توجد نتائج',
  noEntities: 'لا يوجد موردين',
  noResultsHint: 'لا توجد نتائج تطابق معايير البحث.',
  noEntitiesHint: 'ابدأ بإضافة مورد جديد.',
  confirmDeleteMessage: 'هل أنت متأكد من حذف هذا المورد؟',
  deleteSuccess: 'تم حذف المورد بنجاح',
  deleteFailed: 'فشل حذف المورد. يرجى المحاولة مرة أخرى.',
  updateFailed: 'فشل تحديث المورد. يرجى المحاولة مرة أخرى.',
  onlyPaymentTransactionsEditable: AR_LABELS.onlyPaymentTransactionsEditable,
  selectTransactionToEditOrDelete: AR_LABELS.selectTransactionToEditOrDelete,
  editTransaction: AR_LABELS.editTransaction,
  deleteTransaction: AR_LABELS.deleteTransaction,
  confirmDeletePaymentTitle: AR_LABELS.confirmDeletePaymentTitle,
  confirmDeletePaymentMessage: AR_LABELS.confirmDeletePaymentMessage,
  printReceipt: AR_LABELS.printReceipt,
  printSummaryOnly: 'طباعة الملخص فقط',
};
